version: '2'

services:
  pandora-mysql:
    image: pandorafms/pandorafms-mysql:6
    volumes:
      - "./db:/var/lib/mysql:rw"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: "ENTERYOURPASSWD"
      MYSQL_DATABASE: "pandora"
      MYSQL_USER: "pandora"
      MYSQL_PASSWORD: "ENTERYOURPASSWD"
    networks:
      pandora:
        ipv4_address: 172.35.0.2

  pandora-server:
    image: pandorafms/pandorafms-server:6
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./server-config/postfix/main.cf:/etc/postfix/main.cf"
    ports:
      - "41121:41121"
    links:
    - "pandora-mysql:mysql"
    networks:
      pandora:
        ipv4_address: 172.35.0.4
    depends_on:
      - pandora-mysql
    environment:
      PANDORA_DB_HOST: "172.35.0.2:3306"
      PANDORA_DB_USER: "pandora"
      PANDORA_DB_PASSWORD: "ENTERYOURPASSWD"

  pandora-console:
    image: pandorafms/pandorafms-console:6
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:80"
      - "8022:8022"
      - "8023:8023"
    networks:
      pandora:
        ipv4_address: 172.35.0.3
    depends_on:
      - pandora-mysql
    links:
    - "pandora-mysql:mysql"
    environment:
      PANDORA_DB_HOST: "172.35.0.2:3306"
      PANDORA_DB_USER: "pandora"
      PANDORA_DB_PASSWORD: "ENTERYOURPASSWD"

  networks:
    pandora:
      driver: bridge
      ipam:
        driver: default
        config:
        -
          subnet: "172.35.0.0/24"
          gateway: "172.35.0.1"